name: Release VSCode Extension

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: Get VSIX file name
        id: get_vsix
        run: echo "VSIX=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_vsix.outputs.VSIX }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}